Upgrade to aws-sdk v3
neofinancial/config-dug pull request #57
Opened 2024-08-21 20:16 UTC by iansu

- Upgrade to aws-sdk v3
- Update dependencies
- Increase minimum Node version to 18 (current oldest LTS version)

2024-08-21 21:05 UTC, ScottKayeNeo approved these changes
I will test this in a service later, but I remember the context behind this change, and the async-to-sync magic is great.

2024-08-21 21:05 UTC, ScottKayeNeo commented on src/get-secret.ts
> +    const rawValue = spawnSync('node', [path.join(__dirname, 'secrets-manager.js')], {
Hahaha I love this

2024-08-22 01:12 UTC, AD-Blue approved these changes

2024-08-22 14:02 UTC, AdamTranquilla approved these changes

2024-08-22 17:07 UTC, Lewis65 submitted a review, later dismissed
Thanks for doing this! 🤜

2024-08-23 21:13 UTC, ScottKayeNeo commented
Currently letting this sit in cardinal-service with version `config-dug@1.8.0-next.0`

2024-08-23 21:17 UTC, ScottKayeNeo commented on tsconfig.build.json
> -    "declaration": true,
We need to keep `declaration: true`, otherwise the build doesn't contain type information and TypeScript will complain :/

2024-08-23 21:19 UTC, ScottKayeNeo commented on tsconfig.build.json
> -    "declaration": true,
Testing this now with `1.8.0-next.1`

2024-08-23 21:39 UTC, ScottKayeNeo requested changes
Requesting changes just because of the missing `declaration` setting in the build config - this appears to break the build because there isn't any type information to verify against.  The classic:

```
....ts:2:20 - error TS7016: Could not find a declaration file for module 'config-dug'. '...' implicitly has an 'any' type.
  Try `npm i --save-dev @types/config-dug` if it exists or add a new declaration (.d.ts) file containing `declare module 'config-dug';`

2 import config from 'config-dug';
                     ~~~~~~~~~~~~
```

2024-08-27 20:14 UTC, iansu commented
@ScottKayeNeo I fixed the types issue and published `1.8.0-next.2`

2024-08-27 20:31 UTC, ScottKayeNeo approved these changes

2024-08-29 00:37 UTC, nozomu-koshirae approved these changes
No issues so far with OLS running `1.8.0-next.2`  either!

2024-09-05 20:09 UTC, merged