Initial work for config cat plugin
neofinancial/config-dug pull request #61
Opened 2024-11-19 16:36 UTC by Neo-Malcolm-Fischer

Initial work for the config-cat plugin

2025-01-13 23:25 UTC, AdamTranquilla requested changes
Everything looks great, just the failing test and the semver version

2025-01-13 23:25 UTC, AdamTranquilla commented on packages/plugin-config-cat/CHANGELOG.md
> +## 1.0.0 (TBD)
```suggestion
## 0.1.0 (TBD)
```
Major 1 indicates this is in its release state. I think we should keep it at 0.1.0 for this stage, we could even append -beta/-alpha/-rc etc

2025-01-13 23:25 UTC, AdamTranquilla commented on packages/plugin-config-cat/package.json
> +    "node": ">=18.0.0"
Are we not ready for 20?

2025-01-13 23:25 UTC, AdamTranquilla commented on packages/plugin-config-cat/test/config-cat-plugin.test.ts
> +    await expect(configDug.load()).rejects.toThrowError(
this guy is failing :(

2025-01-14 22:43 UTC, neo-michelepiperni commented on packages/plugin-config-cat/CHANGELOG.md
> +## 1.0.0 (TBD)
We did 1.0.0 for the AWS plugin, maybe we should update

2025-01-14 23:12 UTC, neo-michelepiperni reviewed
Some small typos in the read me

2025-01-14 23:32 UTC, neo-michelepiperni reviewed
Couple other things

2025-01-14 23:32 UTC, neo-michelepiperni commented on packages/plugin-config-cat/src/index.ts
> +    const configs = await this.client.getAllValuesAsync();
Will this get all the feature flags from the organization? Or does the SDK key limit it to a certain project within our org?

2025-01-14 23:32 UTC, neo-michelepiperni commented on packages/plugin-config-cat/src/index.ts
> +  private recordValueOrigins = (values: Record<string, unknown>, origin: string): void => {
If we're using the exact same logic here as another plugin, maybe we should put it in the main config cat project and share it instead

2025-02-06 21:29 UTC, AdamTranquilla approved these changes

2025-02-06 21:38 UTC, neo-michelepiperni approved these changes

2025-02-06 21:40 UTC, Neo-Malcolm-Fischer commented on packages/plugin-config-cat/src/index.ts
> +    const configs = await this.client.getAllValuesAsync();
All from the target project

2025-02-06 21:40 UTC, AdamTranquilla approved these changes

2025-02-06 21:40 UTC, AdamTranquilla commented on packages/plugin-config-cat/package.json
> +  "description": "A ConfigCat plugin for Config Dug",
orrr? 🤔 
```suggestion
  "description": "A Config Dug plugin for ConfigCat",
```

2025-02-06 21:40 UTC, Neo-Malcolm-Fischer commented on packages/plugin-config-cat/src/index.ts
> +  private recordValueOrigins = (values: Record<string, unknown>, origin: string): void => {
Unfortunately I can't guarantee that the logic will be identical

2025-02-06 21:41 UTC, Neo-Malcolm-Fischer commented on packages/plugin-config-cat/package.json
> +  "description": "A ConfigCat plugin for Config Dug",
Rejected

2025-02-06 21:50 UTC, merged